version: '3.4'

services:
  userservice:
    image: userservice
    ports:
        - "5050:80" 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - db
    labels:
        kompose.service.type: nodeport
        kompose.image-pull-policy: "Never"
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
        - 8080:80
    volumes:
        - pgadmin_data:/var/lib/postgresql/data
    environment:
        PGADMIN_DEFAULT_EMAIL: 392873@student.fontys.nl
        PGADMIN_DEFAULT_PASSWORD: password
    labels:
        kompose.service.type: nodeport
  db:
    image: postgres
    container_name: pgsql
    restart: always
    ports:
        - 5432:5432
    volumes:
        - db_volume:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: userskwetter
    labels:
        kompose.service.type: nodeport
volumes:
  db_volume:
  pgadmin_data:  